version: '3.8'

services:
  sql_server:
    image: rapidfort/microsoft-sql-server-2019-ib:latest
    environment:
      SA_PASSWORD: monsupermotdepasse
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    container_name: SqlServer2019